let C=[],S=JSON.parse(localStorage.getItem('masarV2')||'{"done":[],"checks":0,"answers":{}}'),A=document.querySelector('#app');
fetch('content.json').then(r=>r.json()).then(x=>{C=x;home()});function save(){localStorage.setItem('masarV2',JSON.stringify(S))}
const D=[['أكثر غاز في الهواء الجاف؟',['الأكسجين','النيتروجين','ثاني أكسيد الكربون'],1,'تركيب الهواء'],['معظم الطقس يحدث في؟',['التروبوسفير','الميزوسفير','الإكسوسفير'],0,'الطبقات'],['أين يتركز الأوزون الواقي؟',['الستراتوسفير','التروبوسفير','الإكسوسفير'],0,'الأوزون'],['الضغط مع الارتفاع؟',['يزداد','يقل','يثبت'],1,'الضغط'],['انتقال الطاقة بحركة الهواء؟',['الحمل','التوصيل','الانعكاس'],0,'الحرارة'],['بداية الحل التكنولوجي؟',['شراء جهاز','تحديد المشكلة والمعايير والقيود','اختيار الأغلى'],1,'التفكير التكنولوجي']];
function pic(k){let d={gases:['تركيب الهواء','نيتروجين 78%','أكسجين 21%','أرجون 0.93%','CO₂ نحو 0.04%'],layers:['طبقات الغلاف الجوي','إكسوسفير — شديدة التخلخل','ثرموسفير — الشفق والأيونات','ميزوسفير — الشهب','ستراتوسفير — الأوزون','تروبوسفير — الطقس'],ozone:['الأوزون والأشعة فوق البنفسجية','الشمس ← أشعة UV','O₂ + طاقة → O + O','O + O₂ → O₃','الأوزون الواقي يمتص قدرًا كبيرًا من UV'],cycle:['دورة الأوزون','أشعة UV','تفكك O₂','تكوين O₃','توازن التكوين والتفكك'],pollution:['ملوثات الهواء','مصدر الانبعاث','تفاعلات في الجو','رصد التركيز','خفض المصدر'],heat:['انتقال الحرارة','إشعاع من الشمس','توصيل عند السطح','حمل بحركة الهواء','تسخين غير متساوٍ'],pressure:['الضغط والارتفاع','قرب السطح: ضغط أعلى','↑ الارتفاع','جزيئات أقل','ضغط أقل'],wind:['الرياح والرطوبة','ضغط مرتفع → ضغط منخفض','حركة الهواء','بخار الماء','تكاثف وسحب'],greenhouse:['الاحتباس الحراري','إشعاع شمسي داخل','الأرض تصدر تحت الحمراء','غازات الدفيئة تمتص جزءًا','جزء من الطاقة يعود لأسفل'],monitor:['الرصد العلمي','محطات أرضية','حساسات جودة الهواء','أقمار صناعية','مقارنة زمنية ومكانية'],solution:['الاستدامة','حدد المشكلة','قارن البدائل','اختبر الحل','قِس النتيجة وحسّن']};let x=d[k]||['رسم تعليمي','مفهوم','دليل','تطبيق','تقويم'];return `<div class="diagram"><svg viewBox="0 0 760 300"><rect width="760" height="300" rx="18" fill="#f1faf6"/><text x="380" y="45" text-anchor="middle" font-size="25" font-weight="bold" fill="#12313a">${x[0]}</text>${x.slice(1).map((t,i)=>`<rect x="90" y="${75+i*50}" width="${580-i*45}" height="36" rx="10" fill="${i%2?'#9ed3c7':'#176b5b'}"/><text x="110" y="${100+i*50}" font-size="18" fill="${i%2?'#12313a':'white'}">${t}</text>`).join('')}</svg><div class="caption">شكل تعليمي عربي أصلي داخل المنصة</div></div>`}
function home(){A.innerHTML=`<span class="pill">الوحدة الثانية • الغلاف الجوي</span><h1>تعلم يتكيف مع فهمك</h1><p class="lead">شرح عربي مصور، تشخيص، مسارات علاجية وقياسية وإثرائية، أنشطة وتحديات تفكير تكنولوجي.</p><button class="primary" onclick="${S.score==null?'diag()':'unit()'}">${S.score==null?'ابدأ التشخيص':'استكمل التعلم'}</button><div class="grid">${C.map((x,i)=>`<div class="card"><b>الدرس 2-${i+1}</b><h3>${x.t}</h3><p>${x.topics.map(y=>y[0]).join(' • ')}</p></div>`).join('')}</div>`}
function diag(){A.innerHTML=`<h2>الاختبار التشخيصي</h2><p class="lead">يحدد نقطة البداية. البنود الحالية تشغيلية وليست أداة البحث النهائية المحكّمة.</p>${D.map((q,i)=>`<div class="q"><b>${i+1}. ${q[0]}</b>${q[1].map((o,j)=>`<label><input type="radio" name="d${i}" value="${j}"> ${o}</label>`).join('')}</div>`).join('')}<button class="primary" onclick="grade()">حلّل مستواي</button><div id="res"></div>`}
function grade(){let n=0,w=[];for(let i=0;i<D.length;i++){let v=document.querySelector(`input[name=d${i}]:checked`);if(!v)return alert('أجب عن جميع البنود');+v.value===D[i][2]?n++:w.push(D[i][3])}S.score=Math.round(n/D.length*100);S.weak=w;S.path=S.score<50?'مسار علاجي':S.score<80?'مسار قياسي':'مسار إثرائي';save();res.innerHTML=`<div class="feedback"><b>${S.path} — ${S.score}%</b><br>${w.length?'دعم أكبر في: '+w.join('، '):'إتقان أولي مرتفع.'}<br><button class="primary" onclick="unit()">ابدأ الوحدة</button></div>`}
function unit(){A.innerHTML=`<h2>خريطة الوحدة</h2><span class="pill">${S.path||'أكمل التشخيص'}</span><div class="grid">${C.map((x,i)=>`<div class="card"><b>2-${i+1}</b><h3>${x.t}</h3><p>${x.topics.map(y=>y[0]).join(' • ')}</p><div class="bar"><i style="width:${S.done.includes(i)?100:0}%"></i></div><button class="primary" onclick="lesson(${i})">${S.done.includes(i)?'مراجعة':'دخول الدرس'}</button></div>`).join('')}</div>`}function lesson(i){let x=C[i];A.innerHTML=`<span class="pill">${S.path||'مسار قياسي'}</span><h2>الدرس 2-${i+1}: ${x.t}</h2>${S.path==='مسار علاجي'?'<div class="feedback warn"><b>دعم إضافي:</b> اقرأ الشرح، افحص الرسم، ثم نفذ تحقق الفهم قبل الانتقال.</div>':''}${x.topics.map((y,k)=>`<section class="box"><small>المفهوم ${k+1}</small><h3>${y[0]}</h3><p>${y[1]}</p>${pic(y[2])}<div class="check"><b>تحقق ذاتي:</b> هل تستطيع شرح الفكرة بمثال؟ <button onclick="master(this)">نعم</button><button onclick="remedy(this,'${y[0]}')">أحتاج مراجعة</button><span></span></div></section>`).join('')}<section class="box tech"><h3>تحدي التفكير التكنولوجي</h3><p>${x.tech}</p><textarea id="ta" placeholder="اكتب الحل، الأدلة العلمية، والمعايير التي اعتمدت عليها..."></textarea><button class="primary" onclick="finish(${i})">حفظ المهمة وإنهاء الدرس</button></section>`}
function master(b){b.parentElement.querySelector('span').textContent='✓ تم تسجيل الإتقان';S.checks++;save()}function remedy(b,n){b.parentElement.querySelector('span').textContent='المسار العلاجي: راجع الرسم، ثم اشرح «'+n+'» بكلماتك واربطه بمثال واقعي.'}
function finish(i){if(ta.value.trim().length<30)return alert('اكتب إجابة وتبريرًا علميًا أكثر تفصيلًا');S.answers[i]=ta.value;if(!S.done.includes(i))S.done.push(i);save();unit()}
function progress(){A.innerHTML=`<h2>لوحة تقدم الطالب</h2><div class="stats"><div class="card"><small>التشخيص</small><strong>${S.score==null?'—':S.score+'%'}</strong></div><div class="card"><small>المسار</small><strong>${S.path||'—'}</strong></div><div class="card"><small>الدروس المكتملة</small><strong>${S.done.length}/4</strong></div></div><div class="card"><h3>مفاهيم تحتاج تعزيزًا</h3><p>${S.weak?.length?S.weak.join('، '):'لا توجد نقاط ضعف مسجلة أو لم يتم التشخيص.'}</p><h3>تحققات الإتقان المسجلة</h3><p>${S.checks||0}</p></div>`}
function teacher(){A.innerHTML=`<h2>لوحة المعلم — نموذج بحثي</h2><p class="lead">تعرض النسخة النهائية بيانات الطلاب الفعلية. حاليًا تعرض بيانات هذا المتصفح فقط لإثبات منطق التسجيل والتحليل.</p><div class="stats"><div class="card"><small>نتيجة التشخيص</small><strong>${S.score==null?'—':S.score+'%'}</strong></div><div class="card"><small>المسار</small><strong>${S.path||'—'}</strong></div><div class="card"><small>الإنجاز</small><strong>${S.done.length}/4</strong></div></div><div class="card"><h3>سجل قرارات التكيف</h3><p>نقاط الضعف: ${S.weak?.join('، ')||'—'}</p><p>عدد تحققات الإتقان: ${S.checks||0}</p><p>المهام التكنولوجية المحفوظة: ${Object.keys(S.answers||{}).length}</p></div>`}
document.querySelector('nav').innerHTML='<button onclick="home()">الرئيسية</button><button onclick="diag()">التشخيص</button><button onclick="unit()">الوحدة</button><button onclick="progress()">تقدمي</button><button onclick="teacher()">المعلم</button>';
const POST=[
['الطبقة التي تحدث فيها معظم ظواهر الطقس؟',['التروبوسفير','الستراتوسفير','الميزوسفير'],0],
['الدور الأهم للأوزون الستراتوسفيري؟',['امتصاص قدر كبير من UV','زيادة الجاذبية','إنتاج النيتروجين'],0],
['لماذا يقل الضغط غالبًا مع الارتفاع؟',['يقل عمود الهواء فوق النقطة','تختفي الجاذبية','يتوقف الهواء عن الحركة'],0],
['انتقال الحرارة بحركة الهواء يسمى؟',['الحمل','التوصيل','الانعكاس'],0],
['أفضل دليل على نجاح حل لجودة الهواء؟',['قياسات قبل/بعد بمؤشر محدد','شكل الجهاز','رأي المصمم فقط'],0],
['عند مقارنة حلين تقنيين يجب؟',['استخدام معايير وقيود وأدلة','اختيار الأحدث دائمًا','اختيار الأغلى'],0]
];
function login(){A.innerHTML=`<div class="login card"><span class="pill">بدء الجلسة التعليمية</span><h2>بيانات الطالب</h2><p>اكتب اسمًا أو كودًا بحثيًا. لا تستخدم بيانات حساسة.</p><input id="studentName" placeholder="اسم الطالب أو الكود"><input id="studentClass" placeholder="الفصل / المجموعة"><button class="primary" onclick="startStudent()">دخول المنصة</button></div>`}
function startStudent(){let n=studentName.value.trim();if(!n)return alert('اكتب الاسم أو الكود');S.student={name:n,group:studentClass.value.trim()};save();home()}
function studentBar(){return S.student?`<div class="student"><b>${S.student.name}</b><span class="pill">${S.student.group||'طالب'}</span><button class="secondary" onclick="logout()">إنهاء الجلسة</button></div>`:''}
function logout(){if(confirm('إنهاء الجلسة الحالية؟')){localStorage.removeItem('masarV2');location.reload()}}
const oldHome=home;home=function(){if(!S.student)return login();oldHome();A.insertAdjacentHTML('afterbegin',studentBar()+`<div class="feedback"><b>رحلة التعلم:</b> تشخيص قبلي ← مسار تكيفي ← 4 دروس ← تقويمات تكوينية ← مهام تفكير تكنولوجي ← تقويم ختامي.</div>`)}
const oldUnit=unit;unit=function(){if(!S.student)return login();oldUnit();A.insertAdjacentHTML('afterbegin',studentBar())}
const oldProgress=progress;progress=function(){if(!S.student)return login();oldProgress();A.insertAdjacentHTML('afterbegin',studentBar());A.insertAdjacentHTML('beforeend',`<div class="card"><h3>الخطوة التالية</h3><p>${S.done.length===4?'أكملت الدروس. انتقل إلى التقويم الختامي.':'استكمل الدروس غير المكتملة ثم نفذ التقويم الختامي.'}</p>${S.done.length===4?'<button class="primary" onclick="postTest()">التقويم الختامي</button>':''}</div>`)}
function postTest(){A.innerHTML=studentBar()+`<h2>التقويم الختامي للوحدة</h2><p class="lead">تقويم تعليمي داخل المنصة لقياس الإتقان بعد التعلم. لا يُعد أداة الدراسة النهائية إلا بعد التحكيم والإجراءات السيكومترية.</p>${POST.map((q,i)=>`<div class="q"><b>${i+1}. ${q[0]}</b>${q[1].map((o,j)=>`<label><input type="radio" name="p${i}" value="${j}"> ${o}</label>`).join('')}</div>`).join('')}<button class="primary" onclick="gradePost()">إظهار التقرير</button>`}
function gradePost(){let n=0;for(let i=0;i<POST.length;i++){let v=document.querySelector(`input[name=p${i}]:checked`);if(!v)return alert('أجب عن جميع البنود');if(+v.value===POST[i][2])n++}S.post=Math.round(n/POST.length*100);save();report()}
function report(){A.innerHTML=studentBar()+`<div class="finalcard"><span class="pill">تقرير التعلم</span><h2>${S.student?.name||'الطالب'}</h2><p>المسار: ${S.path||'—'} • التشخيص: ${S.score??'—'}% • التقويم الختامي: ${S.post??'—'}%</p><p>الدروس المكتملة: ${S.done.length}/4 • تحققات الإتقان: ${S.checks||0} • مهام التفكير التكنولوجي: ${Object.keys(S.answers||{}).length}/4</p></div><div class="card"><h3>ملاحظة بحثية</h3><p>هذا التقرير خاص بالتعلم داخل المنصة. الاختبارات المستخدمة في الدراسة الفعلية يجب أن تكون النسخ النهائية التي تم تحكيمها والتحقق من صدقها وثباتها.</p></div>`}
const oldTeacher=teacher;teacher=function(){if(!S.student)return login();oldTeacher();A.insertAdjacentHTML('afterbegin',studentBar());A.insertAdjacentHTML('beforeend',`<div class="card"><h3>إجابات مهام التفكير التكنولوجي</h3>${C.map((x,i)=>`<p><b>2-${i+1}:</b> ${S.answers?.[i]||'لم تُسلّم بعد'}</p>`).join('')}</div><div class="card"><h3>Rubric مقترح للتفكير التكنولوجي</h3><table class="rubric"><tr><th>البعد</th><th>ما يُبحث عنه</th></tr><tr><td>تحديد المشكلة</td><td>صياغة واضحة للمشكلة والهدف</td></tr><tr><td>المعايير والقيود</td><td>ذكر معايير قابلة للتقييم وقيود واقعية</td></tr><tr><td>البدائل</td><td>اقتراح أكثر من حل عند الحاجة</td></tr><tr><td>القرار بالأدلة</td><td>ربط الاختيار بمفهوم علمي أو بيانات</td></tr><tr><td>التحسين</td><td>اقتراح اختبار أو تعديل للحل</td></tr></table></div>`)}
document.querySelector('nav').innerHTML='<button onclick="home()">الرئيسية</button><button onclick="diag()">التشخيص</button><button onclick="unit()">الوحدة</button><button onclick="progress()">تقدمي</button><button onclick="postTest()">الختامي</button><button onclick="teacher()">المعلم</button>';
if(!S.student)login();
