const L=[
{t:'مكونات وطبقات الغلاف الجوي',f:'تركيب الهواء • الطبقات • الأوزون • سرعة الإفلات',c:[['تركيب الهواء','يتكون الهواء الجاف أساسًا من النيتروجين بنحو 78% والأكسجين بنحو 21%، مع الأرجون وثاني أكسيد الكربون وغازات أخرى بنسب صغيرة.'],['الطبقات','التروبوسفير للطقس، الستراتوسفير لمنطقة الأوزون، الميزوسفير لاحتراق معظم الشهب، الثرموسفير لمناطق متأينة والشفق، والإكسوسفير شديدة التخلخل.'],['سرعة الإفلات','ترتبط قدرة الجرم على الاحتفاظ بالغازات بجاذبيته وسرعة الإفلات؛ انخفاضها يجعل فقد الغازات أسهل.']],tech:'اختر الطبقة الأنسب لرصد ظاهرة جوية وبرر قرارك.'},
{t:'التفاعلات الكيميائية في الغلاف الجوي',f:'تفاعلات ضوئية • الأوزون • الملوثات',c:[['التفاعلات الضوئية','يمكن لطاقة الضوء أن تبدأ تفاعلات جوية بتفكيك جزيئات أو تكوين نواتج جديدة.'],['الأوزون','الأوزون في الستراتوسفير واقٍ من جزء كبير من الأشعة فوق البنفسجية، بينما قد يكون قرب سطح الأرض ملوثًا ضارًا.'],['تفاعلات الملوثات','قد تدخل أكاسيد النيتروجين والكبريت ومركبات أخرى في تفاعلات تسهم في الضباب الدخاني أو الترسيب الحمضي.']],tech:'حلل مصدر تلوث واختر وسيلة رصد أو خفض مناسبة.'},
{t:'العوامل الفيزيائية وتأثيرها في الغلاف الجوي',f:'الحرارة • الضغط • الرياح • الرطوبة',c:[['انتقال الطاقة','تنتقل الطاقة بالإشعاع والتوصيل والحمل، ويسهم التسخين غير المتساوي في فروق الكثافة والضغط.'],['الضغط','ينتج الضغط الجوي عن وزن عمود الهواء ويقل عمومًا مع الارتفاع، ويقاس بأدوات مثل البارومتر.'],['الرياح والرطوبة','تتحرك كتل الهواء استجابة لفروق الضغط، وترتبط الرطوبة ببخار الماء والتكاثف والسحب والطقس.']],tech:'صمم محطة طقس مدرسية وحدد المتغيرات والحساسات.'},
{t:'الغلاف الجوي ودور العلم في استدامته',f:'الرصد • جودة الهواء • الحلول المستدامة',c:[['الرصد العلمي','تقييم الغلاف الجوي يحتاج قياسات قابلة للمقارنة عبر الزمن والمكان باستخدام محطات وأجهزة استشعار ورصد عن بعد.'],['الاستدامة','تشمل الحلول خفض مصادر الملوثات ورفع الكفاءة والبدائل الأنظف مع تقييم الفاعلية والتكلفة والآثار الجانبية.'],['القرار التكنولوجي','يبدأ الحل بتحديد المشكلة والمعايير والقيود، ثم مقارنة البدائل واختبارها وتحسينها بالأدلة.']],tech:'ابنِ خطة تقنية لتحسين جودة الهواء حول المدرسة مع مؤشرات قبل/بعد.'}
];
const D=[['أكثر غاز في الهواء الجاف؟',['الأكسجين','النيتروجين','CO2'],1,'تركيب الهواء'],['معظم الطقس يحدث في؟',['التروبوسفير','الميزوسفير','الإكسوسفير'],0,'الطبقات'],['تفاعل يبدأ بطاقة الضوء؟',['ضوئي','ميكانيكي','توصيل'],0,'التفاعلات'],['الضغط مع الارتفاع؟',['يزداد','يقل','ثابت'],1,'الضغط'],['انتقال الطاقة بحركة المائع؟',['الحمل','التوصيل','الانعكاس'],0,'الحرارة'],['أول خطوة لحل تلوث تقنيًا؟',['شراء جهاز','تحديد المشكلة والمعايير','اختيار الأغلى'],1,'التفكير التكنولوجي']];
let S=JSON.parse(localStorage.getItem('masar')||'{"done":[],"checks":0}');function save(){localStorage.setItem('masar',JSON.stringify(S))}
function show(p){if(p==='home')home();if(p==='diag')diag();if(p==='unit')unit();if(p==='progress')progress();scrollTo(0,0)}
function home(){app.innerHTML=`<span class="pill">الوحدة الثانية • الغلاف الجوي</span><h1>منصة تعلم تكيفي واحدة للوحدة كاملة</h1><p class="lead">تشخيص شامل، أربعة دروس، تقويمات قصيرة، مهام تفكير تكنولوجي، وحفظ لتقدم الطالب.</p><button class="primary" onclick="show('${S.score==null?'diag':'unit'}')">${S.score==null?'ابدأ التشخيص':'استكمل مساري'}</button><div class="grid">${L.map((x,i)=>`<div class="card"><b>2-${i+1} ${x.t}</b><p>${x.f}</p></div>`).join('')}</div>`}
function qs(){return D.map((q,i)=>`<div class="q"><b>${i+1}. ${q[0]}</b>${q[1].map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${o}</label>`).join('')}</div>`).join('')}
function diag(){app.innerHTML=`<h2>التشخيص القبلي للوحدة</h2><p class="lead">نسخة تشغيلية لاختبار منطق التكيف وليست أداة البحث النهائية.</p>${qs()}<button class="primary" onclick="grade()">حلّل مستواي</button><div id="res"></div>`}
function grade(){let n=0,w=[];for(let i=0;i<D.length;i++){let v=document.querySelector(`input[name=q${i}]:checked`);if(!v)return alert('أجب عن كل الأسئلة');+v.value===D[i][2]?n++:w.push(D[i][3])}S.score=Math.round(n/D.length*100);S.weak=w;S.path=S.score<50?'مسار الدعم':S.score<80?'المسار القياسي':'المسار المتقدم';save();res.innerHTML=`<div class="feedback"><b>${S.path} — ${S.score}%</b><br>${w.length?'سيزيد الدعم في: '+w.join('، '):'إتقان أولي مرتفع.'}<br><button class="primary" onclick="show('unit')">ابدأ الوحدة</button></div>`}
function unit(){app.innerHTML=`<h2>دروس الوحدة</h2><span class="pill">${S.path||'أكمل التشخيص أولًا'}</span><div class="grid">${L.map((x,i)=>`<div class="card"><b>الدرس 2-${i+1}</b><h3>${x.t}</h3><p>${x.f}</p><div class="bar"><i style="width:${S.done.includes(i)?100:0}%"></i></div><button class="primary" onclick="lesson(${i})">${S.done.includes(i)?'راجع الدرس':'ابدأ الدرس'}</button></div>`).join('')}</div>`}
function lesson(i){let x=L[i];app.innerHTML=`<span class="pill">${S.path||'المسار القياسي'}</span><h2>2-${i+1} ${x.t}</h2><p class="lead">${x.f}</p>${S.path==='مسار الدعم'?`<div class="feedback warn"><b>دعم إضافي مفعّل:</b> اقرأ كل مفهوم ثم نفذ التحقق قبل الانتقال.</div>`:''}${x.c.map((c,k)=>`<div class="box"><small>المفهوم ${k+1}</small><h3>${c[0]}</h3><p>${c[1]}</p><div class="check"><b>تحقق:</b> هل تستطيع شرح الفكرة بمثال؟ <button onclick="ok(this)">نعم</button><button onclick="retry(this)">أحتاج مراجعة</button><span></span></div></div>`).join('')}<div class="box tech"><h3>تحدي التفكير التكنولوجي</h3><p>${x.tech}</p><textarea id="ans" placeholder="اكتب قرارك والتبرير العلمي..."></textarea><button class="primary" onclick="finish(${i})">احفظ المهمة وأنهِ الدرس</button></div>`}
function ok(b){b.parentElement.querySelector('span').textContent=' ✓ تم تسجيل الإتقان';S.checks++;save()}function retry(b){b.parentElement.querySelector('span').textContent=' راجع الفكرة ثم حاول صياغتها بطريقتك.'}
function finish(i){if(ans.value.trim().length<15)return alert('اكتب تبريرًا مختصرًا قبل الإنهاء');if(!S.done.includes(i))S.done.push(i);save();unit()}
function progress(){app.innerHTML=`<h2>لوحة تقدم الطالب</h2><div class="stats"><div class="card"><small>التشخيص</small><strong>${S.score==null?'—':S.score+'%'}</strong></div><div class="card"><small>المسار</small><strong>${S.path||'—'}</strong></div><div class="card"><small>الدروس المكتملة</small><strong>${S.done.length}/4</strong></div></div><div class="card"><h3>مفاهيم تحتاج تعزيزًا</h3><p>${S.weak?.length?S.weak.join('، '):S.score!=null?'لا توجد نقاط ضعف ظاهرة في التشخيص.':'لم يتم التشخيص.'}</p><h3>تحققات الإتقان المسجلة</h3><p>${S.checks||0}</p></div>`}home();