const questions=[
{q:"أي وصف يعبّر بصورة أفضل عن النموذج العلمي؟",o:["حقيقة لا تتغير","تمثيل يساعد على تفسير ظاهرة ويمكن تطويره","صورة جمالية فقط"],a:1,concept:"النماذج العلمية"},
{q:"عند تصميم حل تقني لمشكلة، ما الخطوة الأهم أولًا؟",o:["اختيار أجمل شكل","تحديد المشكلة والقيود والمعايير","شراء الأدوات"],a:1,concept:"التصميم التكنولوجي"},
{q:"ما أفضل دليل للمفاضلة بين حلين تقنيين؟",o:["رأي شخص واحد","اختبار الحلين وفق معايير قابلة للقياس","اختيار الأرخص دائمًا"],a:1,concept:"التقييم القائم على الدليل"},
{q:"إذا أظهرت التجربة نتيجة غير متوقعة، ماذا تفعل؟",o:["أحذف النتيجة","أراجع الفرض والإجراء والبيانات","أكرر نفس الإجابة"],a:1,concept:"التفكير العلمي"}];
const modules={
support:[["تهيئة المفاهيم","شرح بصري مبسط وأمثلة موجهة"],["مختبر مصغر","نشاط خطوة بخطوة مع تلميحات"],["تحقق سريع","أسئلة قصيرة وتغذية راجعة تفسيرية"],["تحدي تكنولوجي","مشكلة تطبيقية بعد بلوغ الإتقان"]],
standard:[["مراجعة مركزة","ملخص للمفاهيم التي تحتاج تعزيزًا"],["نشاط استقصائي","جمع أدلة وتفسير النتائج"],["مهمة تصميم","بناء حل وفق معايير وقيود"],["تقويم الإتقان","اختبار قصير يحدد الخطوة التالية"]],
advanced:[["تحدي متقدم","مشكلة مفتوحة متعددة الحلول"],["تحليل الأدلة","مقارنة بدائل وتبرير القرار"],["مشروع تقني","تصميم نموذج وتحسينه"],["تقويم نقل التعلم","تطبيق المفهوم في سياق جديد"]]};
const quiz=document.querySelector("#quiz");
questions.forEach((x,i)=>quiz.insertAdjacentHTML("beforeend",`<div class="question"><h3>${i+1}. ${x.q}</h3>${x.o.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}">${o}</label>`).join("")}</div>`));
document.addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(!b)return;document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelector("#"+b.dataset.view).classList.add("active");scrollTo({top:0,behavior:"smooth"})});
function renderPath(data){document.querySelector("#score").textContent=data.pct+"%";document.querySelector("#level").textContent=data.label;document.querySelector("#pathMessage").textContent=`تم اختيار ${data.label} بناءً على التشخيص. سيعاد ضبطه بعد التقويمات القصيرة.`;document.querySelector("#modules").innerHTML=modules[data.key].map((m,i)=>`<article class="module"><span class="tag">${i===0?"الخطوة الحالية":"الخطوة "+(i+1)}</span><h3>${m[0]}</h3><p>${m[1]}</p><button class="${i===0?"primary":"ghost"}">${i===0?"ابدأ النشاط":"عرض التفاصيل"}</button></article>`).join("")}
document.querySelector("#submitQuiz").onclick=e=>{e.preventDefault();let correct=0,answered=0,weak=[];questions.forEach((x,i)=>{const v=document.querySelector(`input[name="q${i}"]:checked`);if(v){answered++;if(+v.value===x.a)correct++;else weak.push(x.concept)}});if(answered<questions.length){alert("أجب عن جميع الأسئلة أولًا.");return}const pct=Math.round(correct/questions.length*100),key=pct<50?"support":pct<80?"standard":"advanced",label=key==="support"?"مسار الدعم":key==="standard"?"المسار القياسي":"المسار المتقدم",data={pct,key,label,weak};document.querySelector("#result").classList.remove("hidden");document.querySelector("#result").innerHTML=`<b>تم بناء المسار: ${label}</b>${weak.length?"<br>مفاهيم تحتاج تعزيزًا: "+weak.join("، "):"<br>أظهرت إتقانًا أوليًا جيدًا."}`;localStorage.setItem("adaptivePath",JSON.stringify(data));renderPath(data)};
const saved=JSON.parse(localStorage.getItem("adaptivePath")||"null");if(saved)renderPath(saved);